Assets/AXIP/AILIA-MODELS/common/Scripts/AiliaCamera.cs, Assets/AXIP/AILIA-MODELS/common/Scripts/AiliaRenderer.cs
表示部分を毎回Instantiateしないようにしました。
また、AiliaCameraのGetPicels32もバッファを再利用するように変更。ただし、Webカメラが無いので動作は未確認。レビューで問題があれば取り消します。
GCHandle.Allocについて、確信はないが新たにAllocしているわけではなさそう（キャッシュをしている？）なので保留。
=> Alloc reduction

Assets/AXIP/AILIA-MODELS/common/Scripts/AiliaCamera.cs, Assets/AXIP/AILIA-MODELS/common/Scripts/AiliaDownload.cs, Assets/AXIP/AILIA-MODELS/common/Scripts/AiliaRenderer.cs, Assets/AXIP/AILIA-MODELS/lightweight-human-pose-estimation/AiliaPoseEstimatorSample.cs, Assets/AXIP/AILIA-MODELS/resnet50/AiliaClassifierLabel.cs, Assets/AXIP/AILIA-MODELS/resnet50/AiliaClassifierSample.cs, Assets/AXIP/AILIA-MODELS/vggface2/AiliaFeatureExtractorSample.cs, Assets/AXIP/AILIA-MODELS/yolov3-face/AiliaDetectorFaceSample.cs, Assets/AXIP/AILIA-MODELS/yolov3-tiny/AiliaDetectorSample.cs, Assets/AXIP/AILIA/Scripts/Api/Ailia.cs, Assets/AXIP/AILIA/Scripts/Api/AiliaClassifier.cs, Assets/AXIP/AILIA/Scripts/Api/AiliaDetector.cs, Assets/AXIP/AILIA/Scripts/Api/AiliaFeatureExtractor.cs, Assets/AXIP/AILIA/Scripts/Api/AiliaFormat.cs, Assets/AXIP/AILIA/Scripts/Api/AiliaPoseEstimator.cs, Assets/AXIP/AILIA/Scripts/Models/AiliaClassifierModel.cs, Assets/AXIP/AILIA/Scripts/Models/AiliaDetectorModel.cs, Assets/AXIP/AILIA/Scripts/Models/AiliaFeatureExtractorModel.cs, Assets/AXIP/AILIA/Scripts/Models/AiliaModel.cs, Assets/AXIP/AILIA/Scripts/Models/AiliaPoseEstimatorModel.cs
=> visual studio code format

Assets/AXIP/AILIA-MODELS/ObjectDetection/AiliaDetectorsSample.cs, Assets/AXIP/AILIA-MODELS/common/Editor/DetectorsSampleInspector.cs, Assets/AXIP/AILIA-MODELS/common/Scripts/AiliaCamera.cs, Assets/AXIP/AILIA-MODELS/common/Scripts/AiliaDownload.cs, Assets/AXIP/AILIA-MODELS/common/Scripts/AiliaImageSource.cs, Assets/AXIP/AILIA-MODELS/common/Scripts/AiliaImageUtil.cs, Assets/AXIP/AILIA-MODELS/common/Scripts/AiliaModelsConst.cs, Assets/AXIP/AILIA-MODELS/common/Scripts/AiliaRenderer.cs, Assets/AXIP/AILIA-MODELS/common/Scripts/AiliaVideoSource.cs, Assets/AXIP/AILIA-MODELS/lightweight-human-pose-estimation/AiliaPoseEstimatorSample.cs, Assets/AXIP/AILIA-MODELS/resnet50/AiliaClassifierLabel.cs, Assets/AXIP/AILIA-MODELS/resnet50/AiliaClassifierSample.cs, Assets/AXIP/AILIA-MODELS/vggface2/AiliaFeatureExtractorSample.cs, Assets/AXIP/AILIA-MODELS/yolov3-face/AiliaDetectorFaceSample.cs, Assets/AXIP/AILIA-MODELS/yolov3-tiny/AiliaDetectorSample.cs, Assets/AXIP/AILIA/Editor/PostBuildProcessAILIA.cs, Assets/AXIP/AILIA/Scripts/Api/Ailia.cs, Assets/AXIP/AILIA/Scripts/Api/AiliaClassifier.cs, Assets/AXIP/AILIA/Scripts/Api/AiliaDetector.cs, Assets/AXIP/AILIA/Scripts/Api/AiliaFeatureExtractor.cs, Assets/AXIP/AILIA/Scripts/Api/AiliaFormat.cs, Assets/AXIP/AILIA/Scripts/Api/AiliaPoseEstimator.cs, Assets/AXIP/AILIA/Scripts/Models/AiliaClassifierModel.cs, Assets/AXIP/AILIA/Scripts/Models/AiliaDetectorModel.cs, Assets/AXIP/AILIA/Scripts/Models/AiliaFeatureExtractorModel.cs, Assets/AXIP/AILIA/Scripts/Models/AiliaModel.cs, Assets/AXIP/AILIA/Scripts/Models/AiliaPoseEstimatorModel.cs
=> namespace : ailiaSDK

Assets/AXIP/AILIA-MODELS/ObjectDetection/AiliaDetectorsSample.cs, Assets/AXIP/AILIA-MODELS/ObjectDetection/detector.unity, Assets/AXIP/AILIA-MODELS/common/Editor/DetectorsSampleInspector.cs, Assets/AXIP/AILIA-MODELS/common/Scripts/AiliaDownload.cs, Assets/AXIP/AILIA-MODELS/common/UI/UiCanvas.prefab
Add download progress bar to UICanvas, and show the progress bar only when files need to be downloaded.
=> Implement the  downloader progressbar of yolov3-tiny and yolov3-face model.

Assets/AXIP/AILIA-MODELS/ObjectDetection/AiliaDetectorsSample.cs
ObjectionDetectorのClassifierを整理して共通のClassifierにしました。
=> Detector classifier integrate

README.md
=> Add supported model to README

Assets/AXIP/AILIA-MODELS/ObjectDetection/AiliaDetectorsSample.cs
=> Fix null pointer exception on macOS caused by camera delay

Assets/AXIP/AILIA-MODELS/ImageSegmentation/AiliaImageSegmentationSample.cs, Assets/AXIP/AILIA-MODELS/ImageSegmentation/ImageSegmentationSample.unity, Assets/AXIP/AILIA-MODELS/common/Scripts/AiliaCamera.cs
We supported camera mode for u2net
=> Implement camera mode to segmentation model

Assets/AXIP/AILIA-MODELS/common/ComputeShader/InputDataProcessing.compute
=> Fix shader warning

Assets/AXIP/AILIA-MODELS/FaceIdentification/AiliaFeatureExtractorSample.cs
=> Fix arcface model download

Assets/AXIP/AILIA-MODELS/FaceDetection/AiliaBlazeface.cs
=> Fix blazeface preprocess

Assets/AXIP/AILIA-MODELS/SuperResolution/AiliaSuperResolutionSample.cs
=> Set low memory mode

Assets/AXIP/AILIA-MODELS/AudioProcessing/AiliaAudioProcessingSample.cs, Assets/AXIP/AILIA-MODELS/AudioProcessing/AiliaRvc.cs, Assets/AXIP/AILIA-MODELS/AudioProcessing/AiliaRvc.cs.meta, Assets/AXIP/AILIA-MODELS/AudioProcessing/AudioProcessingSample.unity, Assets/AXIP/AILIA-MODELS/AudioProcessing/LICENSE/LICENSE_RVC, Assets/AXIP/AILIA-MODELS/AudioProcessing/LICENSE/LICENSE_RVC.meta, README.md
RVCをaudio_processing_sampleに追加するPRです。AudioClipを入力してAudioClipを出力します。
#94
=> Implement rvc

Assets/AXIP/AILIA-MODELS/AudioProcessing/AiliaAudioProcessingSample.cs, Assets/AXIP/AILIA-MODELS/AudioProcessing/AiliaRvc.cs, Assets/AXIP/AILIA-MODELS/AudioProcessing/AiliaRvcCrepe.cs, Assets/AXIP/AILIA-MODELS/AudioProcessing/AiliaRvcCrepe.cs.meta, Assets/AXIP/AILIA-MODELS/AudioProcessing/AudioProcessingSample.unity
CREPEを取り込んでf0に対応する。
https://github.com/axinc-ai/ailia-models/issues/1201
=> Implement RVC f0 mode

Assets/AXIP/AILIA-MODELS/AudioProcessing/AiliaAudioProcessingSample.cs, Assets/AXIP/AILIA-MODELS/AudioProcessing/AiliaRvcCrepe.cs
- RVCのbatch_sizeを固定することでcuDNNの高速化
- crepe_tinyに対応
=> Fix batch size, Use crepe tiny

Assets/AXIP/AILIA-MODELS/Diffusion/AiliaDiffusionSample.cs, Assets/AXIP/AILIA-MODELS/Diffusion/AiliaDiffusionStableDiffusion.cs
=> StableDiffusionのoptモデル対応

Assets/AXIP/AILIA-MODELS/NaturalLanguageProcessing.meta, Assets/AXIP/AILIA-MODELS/NaturalLanguageProcessing/AiliaNaturalLanguageProcessingSample.cs, Assets/AXIP/AILIA-MODELS/NaturalLanguageProcessing/AiliaNaturalLanguageProcessingSample.cs.meta, Assets/AXIP/AILIA-MODELS/NaturalLanguageProcessing/AiliaNaturalLanguageProcessingSample.unity, Assets/AXIP/AILIA-MODELS/NaturalLanguageProcessing/AiliaNaturalLanguageProcessingSample.unity.meta, Assets/AXIP/AILIA-MODELS/NaturalLanguageProcessing/AiliaNaturalLanguageProcessingTextEmbedding.cs, Assets/AXIP/AILIA-MODELS/NaturalLanguageProcessing/AiliaNaturalLanguageProcessingTextEmbedding.cs.meta, Assets/AXIP/AILIA-MODELS/NaturalLanguageProcessing/LICENSE.meta, Assets/AXIP/AILIA-MODELS/NaturalLanguageProcessing/LICENSE/LICENSE_MULTILINGUAL_E5, Assets/AXIP/AILIA-MODELS/NaturalLanguageProcessing/LICENSE/LICENSE_MULTILINGUAL_E5.meta, Assets/AXIP/AILIA-MODELS/NaturalLanguageProcessing/LICENSE/LICENSE_SENTENCE_TRANSFORMER_JAPANESE, Assets/AXIP/AILIA-MODELS/NaturalLanguageProcessing/LICENSE/LICENSE_SENTENCE_TRANSFORMER_JAPANESE.meta, Assets/AXIP/AILIA-MODELS/NaturalLanguageProcessing/SampleText.meta, Assets/AXIP/AILIA-MODELS/NaturalLanguageProcessing/SampleText/sample.txt, Assets/AXIP/AILIA-MODELS/NaturalLanguageProcessing/SampleText/sample.txt.meta, Assets/AXIP/AILIA-TOKENIZER.meta, Assets/AXIP/AILIA-TOKENIZER/Api.meta, Assets/AXIP/AILIA-TOKENIZER/Api/AiliaTokenizer.cs, Assets/AXIP/AILIA-TOKENIZER/Api/AiliaTokenizer.cs.meta, Assets/AXIP/AILIA-TOKENIZER/Models.meta, Assets/AXIP/AILIA-TOKENIZER/Models/AiliaTokenizerModel.cs, Assets/AXIP/AILIA-TOKENIZER/Models/AiliaTokenizerModel.cs.meta, README.md
=> Added sentence transformer and e5

Assets/AXIP/AILIA-MODELS/Diffusion/AiliaDiffusionSample.cs, Assets/AXIP/AILIA-MODELS/Diffusion/DiffusionSample.unity, Assets/AXIP/AILIA-MODELS/ImageSegmentation/AiliaImageSegmentationSample.cs, Assets/AXIP/AILIA-MODELS/ImageSegmentation/ImageSegmentationSample.unity, Assets/AXIP/AILIA-MODELS/ImageSegmentation/SampleImage/couple.jpg.meta, Assets/AXIP/AILIA-MODELS/ImageSegmentation/SampleImage/girl.png.meta, Assets/AXIP/AILIA-MODELS/ImageSegmentation/SampleImage/hair.jpg.meta, Assets/AXIP/AILIA-MODELS/ImageSegmentation/SampleImage/hair2.jpg.meta, Assets/AXIP/AILIA-MODELS/ImageSegmentation/SampleImage/modnet.jpg.meta, Assets/AXIP/AILIA-MODELS/ImageSegmentation/SampleImage/road.png.meta, Assets/AXIP/AILIA-MODELS/SuperResolution/AiliaSuperResolutionSample.cs, Assets/AXIP/AILIA-MODELS/SuperResolution/SampleImage/lenna.png.meta, Assets/AXIP/AILIA-MODELS/SuperResolution/SampleImage/real_esrgan.jpg.meta, Assets/AXIP/AILIA-MODELS/SuperResolution/SampleImage/real_esrgan_anime.jpg.meta, Assets/AXIP/AILIA-MODELS/SuperResolution/SuperResolutionSample.unity
=> Fix android image source

Assets/AXIP/AILIA-MODELS/GenerativeAdversarialNetworks/AiliaLipGan.cs
LipGANがBGRオーダで入力すべきところを、RGBオーダで入力していた問題を修正。
=> Fix lipgan to bgr order, Implement bilinear

Assets/AXIP/AILIA-MODELS/AudioProcessing/AiliaAudioProcessingSample.cs, Assets/AXIP/AILIA-MODELS/AudioProcessing/AiliaRvc.cs
=> Implement rvc version

Packages/manifest.json
=> Remove colab

Assets/AXIP/AILIA-MODELS/common/Scripts/AiliaCamera.cs
クロップ後のバッファをメンバに持たせて再利用するように修正。
=> GetPixel32でGCが発生する問題を修正

Packages/manifest.json
バージョン固定を行わず、常に最新のailiaパッケージを使用するように変更。
=> Always use latest version

Assets/AXIP/AILIA-MODELS/PoseEstimation/AiliaBlazepose.cs, Assets/AXIP/AILIA-MODELS/PoseEstimation/AiliaPoseEstimatorsSample.cs, Assets/AXIP/AILIA-MODELS/PoseEstimation/AiliaPoseResnet.cs
=> Disable fp16 for blaze pose fullbody

Assets/AXIP/AILIA-MODELS/Diffusion/AiliaDiffusionInpainting.cs, Assets/AXIP/AILIA-MODELS/Diffusion/AiliaDiffusionSample.cs, Assets/AXIP/AILIA-MODELS/Diffusion/AiliaDiffusionStableDiffusion.cs, Assets/AXIP/AILIA-MODELS/Diffusion/AiliaDiffusionSuperResolution.cs, Assets/AXIP/AILIA-MODELS/Diffusion/DiffusionSample.unity
- StableDiffusionでailiaTokenizerを使用したPrompt設定に対応。
- live_preview引数を導入（previewが不要な場合はAEを実行せずに高速化）
#117
=> Implement tokenizer for stable diffusion

Assets/AXIP/AILIA-MODELS/TextToSpeech/AiliaVoiceSample.cs, Assets/AXIP/AILIA-MODELS/TextToSpeech/License/LICENSE_CMUDICT, Assets/AXIP/AILIA-MODELS/TextToSpeech/License/LICENSE_CMUDICT.meta, Assets/AXIP/AILIA-MODELS/TextToSpeech/License/LICENSE_G2P_EN, Assets/AXIP/AILIA-MODELS/TextToSpeech/License/LICENSE_G2P_EN.meta, Assets/AXIP/AILIA-MODELS/TextToSpeech/License/LICENSE_NLTK, Assets/AXIP/AILIA-MODELS/TextToSpeech/License/LICENSE_NLTK.meta
=> Implement GPT-SoVITS English

Assets/AXIP/AILIA-MODELS/LargeLanguageModel.meta, Assets/AXIP/AILIA-MODELS/LargeLanguageModel/AiliaLargeLanguageModelSample.cs, Assets/AXIP/AILIA-MODELS/LargeLanguageModel/AiliaLargeLanguageModelSample.cs.meta, Assets/AXIP/AILIA-MODELS/LargeLanguageModel/AiliaLargeLanguageModelSample.unity, Assets/AXIP/AILIA-MODELS/LargeLanguageModel/AiliaLargeLanguageModelSample.unity.meta, Assets/AXIP/AILIA-MODELS/LargeLanguageModel/LICENSE.meta, Assets/AXIP/AILIA-MODELS/LargeLanguageModel/LICENSE/LICENSE_GEMMA2, Assets/AXIP/AILIA-MODELS/LargeLanguageModel/LICENSE/LICENSE_GEMMA2.meta, Assets/AXIP/AILIA-MODELS/LargeLanguageModel/LICENSE/LICENSE_LLAMA3_2.txt, Assets/AXIP/AILIA-MODELS/LargeLanguageModel/LICENSE/LICENSE_LLAMA3_2.txt.meta, Assets/AXIP/AILIA-MODELS/NaturalLanguageProcessing/AiliaNaturalLanguageProcessingSample.unity, Packages/manifest.json, README.md
ailia-llmのUnity Package (https://github.com/axinc-ai/ailia-llm-unity) を使用したgemma2の推論サンプルです。
gemma2 2bを使用してオフラインでチャットが可能です。
Unityの問題か、InputFieldのOnSubmitが発火しないので、Submitボタンを使用してください。
現在はmacOS、iOS、Windows、Linux、Android（arm64）に対応しています。
ailia-llmはまだv0.1であるため、今後、APIが変更になる予定です。
ailia-llmとailia-sdkを使用することで、音声認識・テキスト生成・音声合成まで、すべてオフラインで完結します。
=> Added gemma2

Assets/AXIP/AILIA-MODELS/AudioProcessing/AiliaAudioProcessingSample.cs
=> Added whisper turbo

Assets/AXIP/AILIA-MODELS/TextToSpeech/AiliaVoiceSample.cs
=> GPT-SoVITSでopt3モデルを使用する

Assets/AXIP/AILIA-MODELS/ImageSegmentation/AiliaImageSegmentationSample.cs, Assets/AXIP/AILIA-MODELS/ImageSegmentation/ImageSegmentationSample.unity, Assets/AXIP/AILIA-MODELS/ImageSegmentation/SegmentAnythingModel.cs, Assets/AXIP/AILIA-MODELS/ImageSegmentation/SegmentationModel.cs, Assets/AXIP/AILIA-MODELS/ImageSegmentation/SegmentationModel.cs.meta, Assets/AXIP/AILIA-MODELS/PoseEstimation/PoseEstimationSample.unity
- WEBカメラ入力に対応
- 既存のセグメンテーションのサンプルもクラス化
=> Added camera support for sam1
